#define OS_LINUX	1
#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define FUNDERSCORE	
#define BUNDERSCORE _
#define NEEDBUNDERSCORE 1
#define NEED2UNDERSCORES 0
#define ZEN
#define L1_CODE_SIZE 32768
#define L1_CODE_ASSOCIATIVE 8
#define L1_CODE_LINESIZE 64
#define L1_DATA_SIZE 32768
#define L1_DATA_ASSOCIATIVE 8
#define L1_DATA_LINESIZE 64
#define L2_SIZE 524288
#define L2_ASSOCIATIVE 8
#define L2_LINESIZE 64
#define L3_SIZE 8388608
#define L3_ASSOCIATIVE 9
#define L3_LINESIZE 64
#define ITB_SIZE 4096
#define ITB_ASSOCIATIVE 0
#define ITB_ENTRIES 64
#define DTB_SIZE 4096
#define DTB_ASSOCIATIVE 0
#define DTB_DEFAULT_ENTRIES 64
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_SSE4A
#define HAVE_AVX
#define HAVE_AVX2
#define HAVE_FMA3
#define HAVE_CFLUSH
#define HAVE_MISALIGNSSE
#define HAVE_FASTMOVU
#define NUM_SHAREDCACHE 1
#define NUM_CORES 1
#define CORE_ZEN
#define CHAR_CORENAME "ZEN"
#define SLOCAL_BUFFER_SIZE	20480
#define DLOCAL_BUFFER_SIZE	32768
#define CLOCAL_BUFFER_SIZE	16384
#define ZLOCAL_BUFFER_SIZE	12288
#define GEMM_MULTITHREAD_THRESHOLD	4
